### ISSUE TITLE
[Bug] "to" keyword parsing seems to be broken

### ISSUE THREAD

**Issue by jqueguiner** [ovh/tsl#23]
curl -d "select('requests_latency_seconds_count').where('role=0').from('2019-01-31T00:00:00+01:00',to='2019-02-01T00:00:00+01:00').finite().sampleBy(1h,last).group(sum).window(delta, 0, 1)" https://DESC:MySuperToken@tsl.GRA1.metrics.ovh.net/v0/query

{"error":"Cannot parsed query: Error when parsing \"to\" in \"from\" function, this variable isn't declared at line 1, char 91"}

quick fix resolution (removing the to= instruction) see below:
curl -d "select('requests_latency_seconds_count').where('role=0').from('2019-01-31T00:00:00+01:00', '2019-02-01T00:00:00+01:00').finite().sampleBy(1h,last).group(sum).window(delta, 0, 1)" https://DESC:MySuperToken@tsl.GRA1.metrics.ovh.net/v0/query

**Comment by aurrelhebert** [comment]
Indeed! Thanks for this issue
