### ISSUE TITLE
ANTLR grammar does not reflect the current state of TSL

### ISSUE THREAD

**Issue by hbs** [ovh/tsl#27]
It seems the ANTLR grammar file is not used by the project which instead uses a handcrafted parser, as a consequence, the grammar file does not seem to be updated whenever the features of the language evolve thus preventing implementations which rely on the ANTLR4 grammar to be up to date.

As an example, functions such as fill and fillValue are not present in the ANTLR files.

Are there any plans to actually use the grammar file for the go implementation so it would be kept up to date?

**Comment by aurrelhebert** [comment]
Oh, thank you! I will add the missing function into our ANTLR grammar ASAP. 

The grammar reflects how the TSL language is parsed. At the moment, we do not have any plan to use the grammar file for our golang parser. It is more a spec to specify how TSL could be supported to query a Time Series Data-Base (as native queries).

Contributions are welcome, of course!

**Comment by aurrelhebert** [comment]
The ANTLR grammar is now up to date and match the TSL 0.0.2 release: https://github.com/ovh/tsl/releases/tag/0.0.2
