### ISSUE TITLE
Create a npm package for TSL with wasm 

### ISSUE THREAD

**Issue by NotBad4U** [ovh/tsl#46]
Following #43, that could be nice to provide an npm package to integrate this project easily in a frontend project.

According to [creating-node-js-modules](https://docs.npmjs.com/creating-node-js-modules) from npm documentation, creating a package seem to be simple.
The requirements are:
- Create a package.json file with a `main` entry
- Propose a js file that will load the `wasm` ... but maybe isn't a good idea and we should let people this "custom" task and just provide an empty `main.js`
- A TravisCI or whatever to recreate the package after each new version published.

**Comment by aurrelhebert** [comment]
closed in #47
