### ISSUE TITLE
Sort series by label or name

### ISSUE THREAD

**Issue by tristan-ovh** [ovh/tsl#67]
Hello,

when I get mutiple series, I cannot predict how the list of series will be sorted. I would like to be able to sort the list of series based on the name or a label of the series. 
This way I am sure series will always be displayed in the same order in Grafana.

Thank you,
Tristan

**Comment by StevenLeRoux** [comment]
Thanks Tristan for your input.

I think we could use a SortMetaBy operator with a special keyword for metric name or labels.
It's basically what's achieved in warpscript with the METASORT function.
