### ISSUE TITLE
TSL implementation on python pandas

### ISSUE THREAD

**Issue by jpmjpmjpm** [ovh/tsl#88]
This is more a question rather than an issue.

I have seen in the [roadmap](https://github.com/ovh/tsl/blob/master/spec/roadmap.md) that an implementation independent from the back-end is foreseen. Has an implementation on top of python pandas been considered? Would it make senses according to you?

Thanks in anticipation for your response.

**Comment by aurrelhebert** [comment]
Hello @jpmjpmjpm,

   At first I adapt TSL to be compatible to Influx backend (and soon with more Time Series data base) with: https://github.com/aurrelhebert/TSL-Adaptor 

   IMO, being compatible with Python pandas, it is more adapting the TSL output format? Do you have an idea on your mind, I would love to see how this can be done.

Best

**Comment by jpmjpmjpm** [comment]
Bonjour [Aurélien](https://github.com/aurrelhebert),

In fact I'm starting an IoT project based on Django/Postgresql for the back-end. I save TS in Django with a very basic model (time/value). However the project (which is targeting manufacturing companies) will be based on anomaly detection in TS. The detection of anomalies can be from 'simple' (simple statistics operators) to more complex (ARIMA, Nueral networks...).

The target is that this is open to the end user with a ReactJS front-end connected to REST APIs to the back-end. The user could enter in the front-end 'a TS language' that would be executed in the back-end. The TSL language you developed could be a start for that for the 'statistical operators'.

If you're OK we could have a call on the topic. Let me konw. We're both French by the way!

Best regards, Jean-Pierre.

**Comment by StevenLeRoux** [comment]
Hello  jpmjpmjpm, 

Glad that TLS could help you with this nice use case  :)
